# Generated by Django 5.0.1 on 2024-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("product_price", models.IntegerField(default=0)),
                ("product_category", models.CharField(default="", max_length=50)),
                ("product_subcategory", models.CharField(default="", max_length=50)),
                ("product_description", models.CharField(max_length=300)),
                ("product_image", models.ImageField(upload_to="products_img")),
            ],
        ),
    ]
